### ISSUE TITLE
Some questions about the paper.

### ISSUE THREAD

**Issue by LHY-HongyangLi** [fengziyue/CVRecon#1]
Hi @fengziyue , this is really a nice work. However, I'm confused with the "C" in "Camera Ray Compensation" in Sec3.2. Is "C" equals to "K-1"?

**Comment by fengziyue** [comment]
Hi @LHY-HongyangLi : 

Thank you for your interest in this work!
"C" is the channel number of the cost volume, which consists of multiple feature-matching similarities from "K-1" reference frames and is down-sampled by an MLP. In our experiments, the K is 8 and C is 14.

Please let me know if you still have any questions!

**Comment by LHY-HongyangLi** [comment]
Thank you for your clarification, I'll close the issue.
