### ISSUE TITLE
Question about Ray Feature

### ISSUE THREAD

**Issue by YuhsiHu** [fengziyue/CVRecon#3]
Hi, thank you for your great work!

In Figure 5 of the paper, I saw that you took the last channel of the vanilla cost volume to get the ray feature. What is the reason for only taking the last channel? Have you tried other numbers? If so, would different numbers affect the results?

Thank you for your time.

**Comment by fengziyue** [comment]
Hi YuhsiHu:

Thank you for your interest in this work!

The standard cost volume consists of the dot product between the keyframe and $K$ reference frames feature, we employ a small MLP to reduce the channel number to $7$. Each of the $7$ channels is an aggregation of all information from all frames. We find that using all $7$ channels to construct the ray context feature only increases $0.002$ of the F1-score but consumes $7$ times memory. We find that only picking one channel performs well enough and which channel to pick does not matter. We'll add more discussion in the main paper for justification and motivation.

**Comment by YuhsiHu** [comment]
Thank you for your quick response! I am really looking forward to reading the camera-ready paper.
I will now close this issue.
