### ISSUE TITLE
Performance on standard MVS benchmarks

### ISSUE THREAD

**Issue by mazeyu** [fengziyue/CVRecon#6]
Hi I am curious how is the performance on standard MVS benchmarks like DTU and Tanks and Temples? especially comparing with those depth-based method you mentioned but did not compare to in the paper

**Comment by fengziyue** [comment]
Hi Zeyu:

Thank you for your interest in this work! I have not tested on those
benchmarks. You are welcome to do so and please let me know how it goes!
Thank you!

Sincerely,
Ziyue Feng
